---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources/ingress-nginx.yaml
  - sources/cert-manager.yaml
  - sources/metrics-server.yaml
  - releases/ingress-nginx.yaml
  - releases/cert-manager.yaml
  - releases/metrics-server.yaml
